### ISSUE TITLE
Crates.io is out of date

### ISSUE THREAD

**Issue by samyak-jain** [Matthias-Fauconneau/static-http-cache#1]
Hey. It looks like your crate: https://crates.io/crates/static-http-cache is on version 0.2.0 whereas this repo is on 0.3.0. Any idea why this is not published? Having a hard time using the crates.io version.

**Comment by Matthias-Fauconneau** [comment]
This repository is a fork, it doesn't show as such on Github because the source repository is on Gitlab.

**Comment by samyak-jain** [comment]
Makes sense. So have you published this as a different crate? This fork seems a bit more actively maintained and it acutally works. The original doesn't seem to work anymore. 
BTW, by original I'm assuming you're talking about this one: https://gitlab.com/Screwtapello/static_http_cache. Let me know if there's a different repo which is more up to date.

**Comment by Matthias-Fauconneau** [comment]
I did not publish it on crates.io.
I'm glad my development is helping you out.
Yes, as listed in crates.io.
I'm not aware of any other versions.

**Comment by samyak-jain** [comment]
Do you have any plans on publishing your version as a separate crate? Currently am using this library by adding the github url as a source. But, it is not possible to publish a crate that way.

**Comment by Matthias-Fauconneau** [comment]
I don't. Feel free to copy it there.

**Comment by samyak-jain** [comment]
Fair enough. Thanks a lot!
